window.MetaData = {
  dailyQuestPool: [
    { id: 'dq1', title: 'Read 10 pages', category: 'Mind', xp: 20 },
    { id: 'dq2', title: 'Listen to 15 minutes of an audiobook', category: 'Mind', xp: 20 },
    { id: 'dq3', title: 'Study a language for 15 minutes', category: 'Mind', xp: 20 },
    { id: 'dq4', title: 'Write a short journal entry', category: 'Mind', xp: 20 },
    { id: 'dq5', title: 'No Shorts / no doomscrolling', category: 'Discipline', xp: 25 },
    { id: 'dq6', title: 'Drink only water or calorie-free drinks', category: 'Body', xp: 20 },
    { id: 'dq7', title: 'Take a walk outside', category: 'Body', xp: 20 },
    { id: 'dq8', title: 'Stretch for 10 minutes', category: 'Body', xp: 20 },
    { id: 'dq9', title: 'Do a short bodyweight session', category: 'Body', xp: 25 },
    { id: 'dq10', title: 'Prepare one solid meal yourself', category: 'Body', xp: 20 },
    { id: 'dq11', title: 'Spend 10 focused minutes on Project Metamorphosis', category: 'Discipline', xp: 25 },
    { id: 'dq12', title: 'Do one small room cleanup', category: 'Discipline', xp: 15 },
    { id: 'dq13', title: 'Go to sleep intentionally tonight', category: 'Discipline', xp: 20 },
    { id: 'dq14', title: 'Wake up and get out of bed without long delay', category: 'Discipline', xp: 20 },
    { id: 'dq15', title: 'Meditate or breathe quietly for 5 minutes', category: 'Mind', xp: 20 },
    { id: 'dq16', title: 'Practice a hobby for 20 minutes', category: 'Mind', xp: 20 },
    { id: 'dq17', title: 'Talk to a friend or family member intentionally', category: 'Social', xp: 20 },
    { id: 'dq18', title: 'Help someone with something practical', category: 'Social', xp: 25 },
    { id: 'dq19', title: 'Spend time with animals or outside life', category: 'Life', xp: 20 },
    { id: 'dq20', title: 'Do one thing that was slightly uncomfortable', category: 'Discipline', xp: 25 },
    { id: 'dq21', title: 'Plan tomorrow before sleeping', category: 'Discipline', xp: 15 },
    { id: 'dq22', title: 'No sugary drink today', category: 'Body', xp: 25 },
    { id: 'dq23', title: 'Read or watch something educational', category: 'Mind', xp: 20 },
    { id: 'dq24', title: 'Practice creativity (writing / mini painting / music)', category: 'Mind', xp: 20 },
    { id: 'dq25', title: 'Ride a bike or do light cardio', category: 'Body', xp: 25 },
    { id: 'dq26', title: 'Do one hygiene / self-care task properly', category: 'Body', xp: 15 },
    { id: 'dq27', title: 'No self-trash-talk for one day', category: 'Mind', xp: 20 },
    { id: 'dq28', title: 'Eat at roughly planned times', category: 'Body', xp: 20 },
    { id: 'dq29', title: 'Do a focused task without multitasking', category: 'Discipline', xp: 20 },
    { id: 'dq30', title: 'Reflect on one good thing from the day', category: 'Mind', xp: 15 }
  ],

  mainQuests: [
    { id: 'mq1', title: 'Read 1 Book', desc: 'Finish one whole book.', steps: 1, xpReward: 80 },
    { id: 'mq2', title: 'Read 3 Books', desc: 'Finish three books total.', steps: 3, xpReward: 120 },
    { id: 'mq3', title: 'Read 5 Books', desc: 'Finish five books total.', steps: 5, xpReward: 160 },
    { id: 'mq4', title: 'Lose 2 kg', desc: 'Cut body weight by two kilos.', steps: 2, xpReward: 100 },
    { id: 'mq5', title: 'Lose 5 kg', desc: 'Cut body weight by five kilos.', steps: 5, xpReward: 140 },
    { id: 'mq6', title: 'Lose 10 kg', desc: 'Cut body weight by ten kilos.', steps: 10, xpReward: 220 },
    { id: 'mq7', title: 'Finish 1 Game', desc: 'Complete one single-player game.', steps: 1, xpReward: 80 },
    { id: 'mq8', title: 'Finish 3 Games', desc: 'Complete three single-player games.', steps: 3, xpReward: 130 },
    { id: 'mq9', title: 'Exercise 10 Times', desc: 'Log ten workouts or strong movement sessions.', steps: 10, xpReward: 120 },
    { id: 'mq10', title: 'Exercise 25 Times', desc: 'Log twenty-five workouts or strong movement sessions.', steps: 25, xpReward: 200 },
    { id: 'mq11', title: 'Cook 10 Quality Meals', desc: 'Prepare ten meals yourself.', steps: 10, xpReward: 100 },
    { id: 'mq12', title: 'Write 20 Journal Entries', desc: 'Log twenty personal entries.', steps: 20, xpReward: 140 },
    { id: 'mq13', title: 'Study 50 Language Sessions', desc: 'Complete fifty focused language sessions.', steps: 50, xpReward: 220 },
    { id: 'mq14', title: 'Swim 10 Times', desc: 'Log ten swimming sessions.', steps: 10, xpReward: 110 },
    { id: 'mq15', title: 'Bike 15 Times', desc: 'Log fifteen bike rides.', steps: 15, xpReward: 130 },
    { id: 'mq16', title: 'Paint 10 Mini Sessions', desc: 'Work on mini painting ten times.', steps: 10, xpReward: 100 },
    { id: 'mq17', title: 'Complete 30 Project Sessions', desc: 'Work on Metamorphosis thirty times.', steps: 30, xpReward: 180 },
    { id: 'mq18', title: 'Donate Plasma 3 Times', desc: 'Track three successful donation days.', steps: 3, xpReward: 150 },
    { id: 'mq19', title: 'Spend 20 Family Days', desc: 'Mark twenty meaningful family days.', steps: 20, xpReward: 150 },
    { id: 'mq20', title: 'Garden / Animal Care 30 Times', desc: 'Track thirty garden or animal-care sessions.', steps: 30, xpReward: 180 }
  ],

  achievements: [
    { id: 'a1', tier: 'easy', title: 'First Step', desc: 'Complete your first quest.', type: 'quests', target: 1 },
    { id: 'a2', tier: 'easy', title: 'Tiny Momentum', desc: 'Complete three total quests.', type: 'quests', target: 3 },
    { id: 'a3', tier: 'easy', title: 'Awakening', desc: 'Gain your first level.', type: 'level', target: 2 },
    { id: 'a4', tier: 'easy', title: 'One Good Day', desc: 'Finish a day with at least one completed quest.', type: 'days', target: 1 },
    { id: 'a5', tier: 'easy', title: 'First Arc', desc: 'Advance any main quest once.', type: 'mainSteps', target: 1 },
    { id: 'a6', tier: 'medium', title: 'Quest Runner', desc: 'Complete ten total quests.', type: 'quests', target: 10 },
    { id: 'a7', tier: 'medium', title: 'Quest Walker', desc: 'Complete twenty-five total quests.', type: 'quests', target: 25 },
    { id: 'a8', tier: 'medium', title: 'Quest Builder', desc: 'Complete fifty total quests.', type: 'quests', target: 50 },
    { id: 'a9', tier: 'medium', title: 'Rising Hero', desc: 'Reach level 5.', type: 'level', target: 5 },
    { id: 'a10', tier: 'medium', title: 'Disciplined Hero', desc: 'Reach level 10.', type: 'level', target: 10 },
    { id: 'a11', tier: 'medium', title: 'Streak Spark', desc: 'Reach a positive streak of 3.', type: 'streak', target: 3 },
    { id: 'a12', tier: 'medium', title: 'Streak Keeper', desc: 'Reach a positive streak of 7.', type: 'streak', target: 7 },
    { id: 'a13', tier: 'medium', title: 'Daily Ritual', desc: 'Accumulate five completed days.', type: 'days', target: 5 },
    { id: 'a14', tier: 'medium', title: 'Steady Week', desc: 'Accumulate ten completed days.', type: 'days', target: 10 },
    { id: 'a15', tier: 'medium', title: 'Mind Over Noise', desc: 'Complete ten Mind-type daily quests.', type: 'dailyCategory', category: 'Mind', target: 10 },
    { id: 'a16', tier: 'medium', title: 'Body Awakens', desc: 'Complete ten Body-type daily quests.', type: 'dailyCategory', category: 'Body', target: 10 },
    { id: 'a17', tier: 'medium', title: 'Iron Will', desc: 'Complete ten Discipline-type daily quests.', type: 'dailyCategory', category: 'Discipline', target: 10 },
    { id: 'a18', tier: 'medium', title: 'Long Arc', desc: 'Reach ten main quest progress steps.', type: 'mainSteps', target: 10 },
    { id: 'a19', tier: 'medium', title: 'Pathwalker', desc: 'Reach twenty-five main quest progress steps.', type: 'mainSteps', target: 25 },
    { id: 'a20', tier: 'medium', title: 'Self System', desc: 'Earn a solid amount of total XP.', type: 'totalXpEarned', target: 500 },
    { id: 'a21', tier: 'legendary', title: 'True Discipline', desc: 'Reach level 20.', type: 'level', target: 20 },
    { id: 'a22', tier: 'legendary', title: 'Relentless', desc: 'Complete one hundred total quests.', type: 'quests', target: 100 },
    { id: 'a23', tier: 'legendary', title: 'Metamorphosis', desc: 'Reach fifty completed days.', type: 'days', target: 50 },
    { id: 'a24', tier: 'legendary', title: 'Never Idle', desc: 'Reach a positive streak of fifteen.', type: 'streak', target: 15 },
    { id: 'a25', tier: 'legendary', title: 'Quiet Self-Trust', desc: 'Advance main quests a total of sixty steps.', type: 'mainSteps', target: 60 }
  ],

  skillOptions: {
    Strength: ['Calisthenics', 'Gym Training', 'Powerlifting Basics', 'Manual Labor', 'Heavy Carrying', 'Wood Chopping', 'Shoveling', 'Push Strength', 'Pull Strength', 'Core Training'],
    Dexterity: ['Typing', 'Drawing', 'Mini Painting', 'Knife Skills', 'DIY Repairs', 'Tool Handling', 'Driving Precision', 'Photography', 'Craft Work', 'First Aid'],
    Agility: ['Running', 'Cycling', 'Swimming', 'Hiking', 'Stretching', 'Mobility Training', 'Dance', 'Football', 'Basketball', 'Table Tennis'],
    Endurance: ['Walking', 'Long Cycling', 'Swimming Endurance', 'Cardio Training', 'Work Stamina', 'Sleep Hygiene', 'Recovery Routine', 'Backpack Hiking', 'Household Chores', 'Gardening'],
    Intelligence: ['Reading', 'Study', 'Language Learning', 'Research', 'Writing', 'Critical Thinking', 'Planning', 'Excel / Spreadsheets', 'Computer Skills', 'Problem Solving'],
    Willpower: ['Meditation', 'No Sugary Drinks', 'No Doomscrolling', 'Routine Keeping', 'Sleep Discipline', 'Cold Showers', 'Impulse Control', 'Stress Management', 'Consistency', 'Task Finishing'],
    Wits: ['Humor', 'Improvisation', 'Roleplay', 'Debate', 'Fast Talking', 'Social Reading', 'Adaptability', 'Creative Problem Solving', 'Conversation Timing', 'Observation'],
    Wisdom: ['Cooking', 'Herbalism', 'Journaling', 'Self-Reflection', 'Emotional Insight', 'Psychology Basics', 'Budgeting', 'Animal Care', 'Gardening', 'Life Balance']
  }
};
